app:
  addr: 172.27.202.125
  port: 9088

mysql:
  mysql_user: "root"
  password: "shaw123"
  mysql_host: "127.0.0.1"
  mysql_port: "3306"
  db_name: "ginknown"

redis:
  redis_host: "127.0.0.1"
  redis_port: "6379"
  redis_db: 0
  redis_passwd:
